### ISSUE TITLE
Crash when ran on a dedicated server.

### ISSUE THREAD

**Issue by Darkhax** [ZeusIGN/CannibalConundrum#1]
I am trying to use 1.0.1 on a dedicated server with Forge 47.1.3 and get the following crash attributed to Cannibal Conundrum. The full crash log has been attached.

[crash-2023-10-31_18.45.29-fml.txt](https://github.com/ZeusIGN/CannibalConundrum/files/13220372/crash-2023-10-31_18.45.29-fml.txt)

**Comment by ZeusIGN** [comment]
Fixed in 1.0.2
